gripper_common:
  force_position_mode: false
  topic: "/end_effector_cmd_lr"
  left_valid: true
  right_valid: false

gripper_commands:
  pick_open:
    mode: torque
    command: open
    torque: 1.0

  pick_close:
    mode: torque
    command: close
    torque: 0.5

  place_open:
    mode: torque
    command: open
    torque: 1.0

  place_close:
    mode: torque
    command: close
    torque: 0.5
